language: android

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-23
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.1
    - android-23
    #- sys-img-x86-android-23
    sys-img-armeabi-v7a-android-23
    - extra-android-support
    - extra-android-m2repository

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e00d2e7f099579331143
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always     # options: [always|never|change] default: always
