language: android
env:
  global:
    - ADB_INSTALL_TIMEOUT=8
android:
  components:
    - platform-tools
    - tools

    - build-tools-23.0.1

    - android-23

    - sys-img-x86-android-23

    - extra-android-support
    - extra-android-m2repository

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e00d2e7f099579331143
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
